name: vocal_trainer_ai
description: "듀얼 AI 엔진 보컬 트레이닝 앱 (CREPE + SPICE)"
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP 클라이언트 (CREPE + SPICE 서버 통신)
  dio: ^5.3.2
  
  # 오디오 처리
  flutter_sound: ^9.28.0
  permission_handler: ^12.0.1
  file_picker: ^6.1.1
  audioplayers: ^5.2.1
  
  # UI
  cupertino_icons: ^1.0.8
  
  # 네트워크 및 디바이스 정보
  connectivity_plus: ^5.0.1
  device_info_plus: ^10.1.0
  package_info_plus: ^8.3.0
  path_provider: ^2.1.1
  
  # 디버그 도구
  fl_chart: ^0.68.0
  
  # 프라이버시 및 보안
  shared_preferences: ^2.2.2
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/
